### PR TITLE
Pul Request 1

### PR DESCRIPTION
**Pull request by nripane**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/commit/9b91b4517557267f6eddb1e0664a3ca81b6beb22%23commitcomment-12392641%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125558987%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125559458%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125562502%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125562796%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125562946%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/commit/9b91b4517557267f6eddb1e0664a3ca81b6beb22%23commitcomment-12393460%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125587654%22%2C%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125587819%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/pull/1%23issuecomment-125558987%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Fix%20test%20file%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A03%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A05%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10771883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nripane%22%7D%7D%2C%20%7B%22body%22%3A%20%22Task1%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A15%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A15%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10771883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nripane%22%7D%7D%2C%20%7B%22body%22%3A%20%22Task2%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A16%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-07-28T12%3A43%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%2C%20%7B%22body%22%3A%20%22New%20Task%22%2C%20%22created_at%22%3A%20%222015-07-28T12%3A43%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Commit%209b91b4517557267f6eddb1e0664a3ca81b6beb22%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc/NeonStaticResources/commit/9b91b4517557267f6eddb1e0664a3ca81b6beb22%23commitcomment-12392641%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22just%20added%20a%20copy%20of%20test.txt%20file%20before%20second%20commit%22%2C%20%22created_at%22%3A%20%222015-07-28T10%3A25%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10771883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nripane%22%7D%7D%2C%20%7B%22body%22%3A%20%22Is%20this%20done%3F%22%2C%20%22created_at%22%3A%20%222015-07-28T11%3A20%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8359869%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/varshacloudlendinginc%22%7D%7D%5D%2C%20%22title%22%3A%20%22Commit%209b91b45%20comments%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-Commit 9b91b4517557267f6eddb1e0664a3ca81b6beb22'></a> &nbsp;<b><a href='https://github.com/varshacloudlendinginc/NeonStaticResources/commit/9b91b4517557267f6eddb1e0664a3ca81b6beb22#commitcomment-12392641'>Commit 9b91b45 comments</a></b>
- <a href='https://github.com/nripane'></a> just added a copy of test.txt file before second commit
- <a href='https://github.com/varshacloudlendinginc'></a> Is this done?
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/varshacloudlendinginc/NeonStaticResources/pull/1#issuecomment-125558987'>General Comment</a></b>
- <a href='https://github.com/varshacloudlendinginc'></a> Fix test file
- <a href='https://github.com/nripane'></a> :+1:
- <a href='https://github.com/varshacloudlendinginc'></a> Task1
- <a href='https://github.com/nripane'></a> :+1:
- <a href='https://github.com/varshacloudlendinginc'></a> Task2
- <a href='https://github.com/varshacloudlendinginc'></a> :+1:
- <a href='https://github.com/varshacloudlendinginc'></a> New Task

<a href='https://www.codereviewhub.com/varshacloudlendinginc/NeonStaticResources/pull/1?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/varshacloudlendinginc/NeonStaticResources/pull/1?approve=1'></a>&nbsp;<a href='https://github.com/varshacloudlendinginc/NeonStaticResources/pull/1'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by varshacloudlendinginc** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/varshacloudlendinginc/NeonStaticResources/pull/1'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by varshacloudlendinginc** [comment]
Fix test file

**Comment by nripane** [comment]
:+1:

**Comment by varshacloudlendinginc** [comment]
:shipit:

**Comment by varshacloudlendinginc** [comment]
:shipit::gun:

**Comment by nripane** [comment]
comment one from nripane

**Comment by varshacloudlendinginc** [comment]
comment 2

**Comment by nripane** [comment]
comment 2 from nripane

**Comment by varshacloudlendinginc** [comment]
comment 3

**Comment by varshacloudlendinginc** [comment]
Task1

**Comment by nripane** [comment]
:+1:

**Comment by varshacloudlendinginc** [comment]
Task2

**Comment by varshacloudlendinginc** [comment]
:+1:

**Comment by varshacloudlendinginc** [comment]
New Task

**Pull request closed without merging**
